### ISSUE TITLE
Input for generateDataIndepth()

### ISSUE THREAD

**Issue by hartmannmark** [gbouland/differential-dropout-analysis#1]
Hello, I am currently testing some of my data walking through your scripts, which is working quiet well so far. However, I have just come across an open question regarding the part: Generate Data Indepth:
https://github.com/gbouland/differential-dropout-analysis/blob/main/002%20Scripts/generateDataIndepth.R

You provide the function generateDataIndepth() but I am not sure what to use as input? Would be great to get an example!

Thanks in advance,
Mark

**Comment by gbouland** [comment]
Hi Mark,
We used that function to quickly compare the results of DDA and DEA across datasets. So `data` is a nested list where the datasets are represented in the first level and in the second level the DDA and DEA results of the respective datasets can be found. In our analysis `data` = “**004 /DDA_DEA_results_all_datasets.rds**”. `summ` requires a list of summary statistics. Our summary statistics can be loaded from “**003 Data/Summary/**”.  `set` requires the names used for each dataset. Provided the names from `data` and `summ` match. To use that function with our results, the following code should work:

```
nothreshDat <- readRDS(file = "./004 Results/DDA_DEA_results_all_datasets.rds")
source("./002 Scripts/generateDataIndepth.R")
dir <- c("./003 Data/Summary")
files <-  list.files(dir)
summ <- lapply(files,function(x)readRDS(sprintf("%s/%s",dir,x)))
names(summ) <- gsub(".rds","",files)
all <- lapply(names(summ),function(x){
                tmpData <- generateDataIndepth(nothreshDat,summ,x)
                tmpData$dataset <- as.character(x)
                tmpData
      }) %>% do.call(what = "rbind")
```
You're probably more interested in your own dataset. As such the code below shows how the summary files were generated  (example with the COVID dataset):

```
set <- readRDS("./COVID.rds")
samplesheet <- set$samplesheet
counts <- set$counts
SeurOBJ <- CreateSeuratObject(counts = counts)
SeurOBJ <- NormalizeData(SeurOBJ, normalization.method = "LogNormalize", scale.factor = 10000)
normalized <- SeurOBJ@assays$RNA@data
allStats <- data.frame("globalMean" = rowMeans(normalized))
allStats$GroupA_Mean <- rowMeans(normalized[,samplesheet[samplesheet$status == "Healthy","IDs"]])
allStats$GroupB_Mean <- rowMeans(normalized[,samplesheet[samplesheet$status == "COVID","IDs"]])
allStats$globalSD <- apply(normalized,1,sd)
allStats$GroupA_SD <- apply(normalized[,samplesheet[samplesheet$status == "Healthy","IDs"]],1,sd)
allStats$GroupB_SD <- apply(normalized[,samplesheet[samplesheet$status == "COVID","IDs"]],1,sd)
allStats$globalZero <- rowSums(normalized[,] == 0) / ncol(normalized)
allStats$GroupA_Zero <- rowSums(normalized[,samplesheet[samplesheet$status == "Healthy","IDs"]] == 0) / ncol(normalized[,samplesheet[samplesheet$status == "Healthy","IDs"]])
allStats$GroupB_Zero <- rowSums(normalized[,samplesheet[samplesheet$status == "COVID","IDs"]] == 0) / ncol(normalized[,samplesheet[samplesheet$status == "COVID","IDs"]])
saveRDS(allStats,file = "./003 Summary/COVID.rds")
```
So for each gene, of both contrasting cell populations it contains the average expression, sd and percentage of zeros.
And `generateDataIndepth()` also identifies per dataset which genes are DDG-only or DEG-only and contrasts the p-value of both tests.

I hope this made things more clear, and good luck with your analysis!

Gerard

**Comment by hartmannmark** [comment]
Great! Thanks for the quick reply! I will give it a try with my own data... :-)

Just to be sure about it, the function is for cross-datasets comparison. That's why it didn't work for me, I guess, because my results `nothreshDat` contain only the DDs and DEGs of a single dataset... Does this make sense?

But at the end you mention that the `generateDataIndepth()` also analysis the unique genes per dataset. So I assume it should still work.

I assembled my results like this. Would be great, if you can have a look on it:

`### Custom preparation of DDs and DEGs results for required nothreshDat object
results <- list("DD" = DDs$all, "wilcox" = DEGs$all)`

DDs$all and `DEGs$all` are the results of:
`DDs <- DDs(data = counts,samplesheet = samplesheet, cells = "all", contrast =  c("1","2"))
DEGs <- DEGs(data = counts, samplesheet = samplesheet, cells = "all", contrast = c("1","2"), test="wilcox")`

Using this `results` object gives the error:
`generateDataIndepth(results)
Error in log10(all_DD$P) : non-numeric argument to mathematical function`

**Comment by gbouland** [comment]
I your case I would not use `generateDataIndepth()` then. 

I would unpack the results from the list.
```
DDA_results <- results$DD
DEA_results <- results$wilcox
```
Then make 100% sure the order of genes in both data.frames match

```
genes <- intersect(rownames(DDA_results), rownames(DEA_results))
DDA_results <- DDA_results[genes,]
DEA_results<- DEA_results[genes,]
```
And then you're already good to go! For instance, you could `cbind` the data.frames and compare the results.

```
combined <- cbind(DDA_results,DEA_results)
combined$p_delta <- log10(combined$P) - log10(combined$p_val)
combined$DDG_only <- ifelse(combined$fdr_DDG <= 0.05 & combined$fdr_DEG>= 0.05,1,0)
combined$DEG_only <- ifelse(combined$fdr_DEG <= 0.05 & combined$fdr_DDG>= 0.05,1,0)
```
And then you basically have the same info as from `generateDataIndepth()`, minus the summary statistics.
For this to work, you probably need to rename some of the colnames.

**Comment by hartmannmark** [comment]
This worked well, thank you very much!
